name: quran_library
description: "An integrated package for displaying the Holy Qur’an identical to
  the Medina Quran with the narration of Hafs on the authority of Asim."
version: 1.2.6
homepage: https://github.com/alheekmahlib/quran_library

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  another_xlider: ^3.0.2
  archive: ^4.0.7
  dio: ^5.8.0+1
  drift: ^2.27.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.4.0
  path: ^1.9.0
  path_provider: ^2.1.5

# This package supports all platforms listed below.
# But note that it works and fits on mobile size devices
# Additional Screen Sizes will be supported later
platforms:
  ? android
  #  web:
  ? ios
  ? linux
  ? macos
  ? windows

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

package_rename_config:
  android:
    package_name: com.alheekmah.quranPackage

  ios:
    bundle_name: com.alheekmah.quranPackage
    package_name: com.alheekmah.quranPackage

  linux:
    package_name: com.alheekmah.quranPackage

  macos:
    package_name: com.alheekmah.quranPackage

flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/Kufam-Regular.ttf
    - assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - assets/fonts/UthmanicHafs_V20.ttf
    - assets/jsons/
    - assets/svg/
    - assets/svg/surah_name/
    - assets/saadiV4.db
    - assets/en.json

  fonts:
    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Regular.ttf
    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - family: hafs
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf
